version: "3.3"

services:  
  php:
    build:
      context: ../..
      dockerfile: DockerFile/laravel10/Dockerfile
    container_name: laravel10slp
    working_dir: /var/www/html/laravel10/slp
    expose:
      - 8010
    ports:
      - 8010:8000
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - ../../../Service/www/laravel10/slp:/var/www/html/laravel10/slp
    networks:
      - serv-test-wt
      - mysql_network-mysql

  mysql:
    image: mysql:5.7.36
    container_name: mysqllaravel10slp
    restart: unless-stopped
    tty: true
    expose:
      - 3307
    ports:
      - 3307:3306
    volumes:
      - ../../../Service/mysql/laravel10/slp:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=slp
      - MYSQL_USER=291022slp
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - serv-test-wt
      - mysql_network-mysql

networks:
  serv-test-wt:
    driver: bridge
  mysql_network-mysql:
    external: true